name: Compliance Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  markdown-style-check:
    name: Markdown Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Check
        # Reject any .md files with tabs in them
        run: |
          if grep -rn "	" * --include=*.md;
          then exit 1
          fi

  # Do not allow merge commits in pull request
  reject-merge-commits:
    if: ${{ github.event_name == 'pull_request' }}
    name: Reject Merge Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: motlin/forbid-merge-commits-action@v1.0.6
        with:
            fail-on-merge-commits: true

  uncrustify:
    name: Style Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Install uncrustify
        run: |
          sudo apt update
          sudo apt install --no-install-recommends -y uncrustify
      - name: Checkout
        uses: actions/checkout@v5
      - name: Check
        # Run an uncrustify check. If the check indicates problems, then apply the fixes and show the diff.
        run: |
          set +e
          ./.github/script/style_checker.sh --check
          if [ $? -ne 0 ]; then
            set -e
            ./.github/script/style_checker.sh
            git diff
            exit 1
          fi

  file-encoding:
    name: File Encoding Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Check
        run: |
          set +e
          ./script/check_encode.sh
          if [ $? -ne 0 ]; then
            exit 1
          fi

  copyright-date:
    name: Check Copyright Year
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Check
        run: |
          set +e
          ./script/check_copyright_date.sh
          if [ $? -ne 0 ]; then
            exit 1
          fi
